package com.example.keeper.systems.notification.enums;

public enum NotificationType {

    // Document
    DOCUMENT_LIKED,
    DOCUMENT_FEEDBACKED,
    DOCUMENT_SAVED,
    DOCUMENT_VERSION_PENDING,
    DOCUMENT_VERSION_APPROVED,
    DOCUMENT_VERSION_REJECTED,

    // Quiz
    QUIZ_LIKED,
    QUIZ_SAVED,
    QUIZ_COMPLETED,

    // Flashcard
    FLASHCARD_LIKED,
    FLASHCARD_SAVED,
    FLASHCARD_COMPLETED,

    // Group
    GROUP_INVITED,
    GROUP_MEMBER_JOINED,
    GROUP_MEETING_CREATED,
    GROUP_DOCUMENT_ADDED,

    // Follow
    FOLLOW,
    NEW_DOCUMENT,

    // Workspace
    WORKSPACE_INVITED,
    WORKSPACE_MEMBER_JOINED,
    WORKSPACE_DOCUMENT_ADDED,
    WORKSPACE_DOCUMENT_DELETED,
    WORKSPACE_UPDATED,
    WORKSPACE_INVITATION_ACCEPTED,
    PRO_UPGRADE_SUCCESS
}
