import React, { useState, useRef } from "react";
import { UploadCloud, FileText, X, Send, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import axiosClient from "@/api/axiosClient";
import FlashcardItem from "./FlashcardItem"; 

export default function AIFlashcardGenerator() {
  const [inputText, setInputText] = useState("");
  const [file, setFile] = useState(null);
  const fileInputRef = useRef(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [flashcards, setFlashcards] = useState([]);

  const handleFileSelect = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile) setFile(selectedFile);
  };

  const handleGenerate = async () => {
    if (!inputText && !file) return;

    setIsGenerating(true);
    const formData = new FormData();
    if (file) formData.append("document", file);
    if (inputText) formData.append("text", inputText);

    try {
      const response = await axiosClient.post("/api/ai/flashcards/generate", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });

      const result = response.data.data || response.data;
      if (Array.isArray(result)) {
        setFlashcards(result);
      } else {
        alert("Data returned is not in the correct format!");
      }
    } catch (error) {
      console.error("Error:", error);
      alert("Error occurred while generating flashcards!");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    // Sử dụng container tối ưu cho dashboard
    <div className="max-w-5xl mx-auto space-y-10">
      
      {/* Header trang */}
      <div className="flex flex-col items-center text-center space-y-2">
        <div className="bg-orange-100 p-3 rounded-full text-[#f26522]">
          <BookOpen className="h-8 w-8" />
        </div>
        <h1 className="text-3xl font-bold text-slate-800">AI Flashcard Generator</h1>
        <p className="text-slate-500">Learn smarter with flashcards generated by AI</p>
      </div>

      {/* Card Input */}
      <Card className="w-full max-w-2xl mx-auto border-slate-200 shadow-sm rounded-2xl overflow-hidden">
        <CardContent className="p-6 space-y-4">
          <textarea
            className="w-full p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-[#f26522] outline-none transition-all resize-none"
            placeholder="Paste your lesson content or questions here..."
            rows={5}
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
          />

          {file && (
            <div className="flex items-center gap-2 p-2 bg-slate-50 border border-slate-100 rounded-lg w-fit text-sm animate-in fade-in slide-in-from-bottom-2">
              <FileText className="h-4 w-4 text-[#f26522]" />
              <span className="truncate max-w-[200px]">{file.name}</span>
              <X className="h-4 w-4 cursor-pointer hover:text-red-500" onClick={() => setFile(null)} />
            </div>
          )}

          <div className="flex justify-between items-center pt-2">
            <input type="file" ref={fileInputRef} onChange={handleFileSelect} className="hidden" />
            <Button variant="outline" className="rounded-xl border-slate-200 hover:bg-slate-50" onClick={() => fileInputRef.current.click()}>
              <UploadCloud className="h-4 w-4 mr-2" /> Select Document
            </Button>

            <Button className="bg-[#f26522] hover:bg-[#d95316] rounded-xl px-6" onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? "AI is generating..." : "Generate Now"}
              <Send className="h-4 w-4 ml-2" />
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Grid kết quả */}
      {flashcards.length > 0 && (
        <div className="space-y-6">
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <h3 className="text-xl font-bold text-slate-700">Your Results</h3>
            <span className="text-sm bg-[#f26522]/10 text-[#f26522] px-4 py-1 rounded-full font-medium">
              {flashcards.length} card created
            </span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {flashcards.map((item, index) => (
              <FlashcardItem 
                key={index} 
                term={item.term} 
                definition={item.definition} 
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}