spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/keeper
spring.datasource.username=postgres
spring.datasource.password=password

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=create-drop
=======
spring.jpa.hibernate.ddl-auto=create
>>>>>>> a6e8b55 (Refactor AI Chat interface and fix project workspace crash)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thunee0411@gmail.com
spring.mail.password=bdtvnjpgrnenutpo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8