spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/keeper
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thunee0411@gmail.com
spring.mail.password=bdtvnjpgrnenutpo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

gemini.api.key=${GEMINI_API_KEY}